# Generated by Django 4.1.2 on 2023-04-14 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_of_relative',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
